### ISSUE TITLE
Unable to transfer key

### ISSUE THREAD

**Issue by cynojien** [full-disclosure/android-luks#4]
Hi!

I love the idea behind this app. When I try to use the add_key script the app will open and I tap on unlock. After verifying the script states "Coulnd't get the key. Please unplug the phone, kill the app and retry"

If I run the android LUKS program on it's own, nothing appears on stdout when using the Unlock function from the app.

I have tried multiple USB cable and 2 different phones. 

If there is any way for me to provide a log with the host application I'd be happy to provide it.

I can provide a logcat output if needed too.

**Comment by cynojien** [comment]
Logcat crash

```
FATAL EXCEPTION: AccessoryController
Process: eu.fulldisclosure.android.luks, PID: 31836
java.lang.IllegalStateException: IV has already been used. Reusing IV in encryption mode violates security best practices.
	at android.security.keystore2.AndroidKeyStoreUnauthenticatedAESCipherSpi.addAlgorithmSpecificParametersToBegin(AndroidKeyStoreUnauthenticatedAESCipherSpi.java:272)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.addAlgorithmSpecificParametersToBegin(AndroidKeyStoreCipherSpiBase.java:1047)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.ensureKeystoreOperationInitialized(AndroidKeyStoreCipherSpiBase.java:341)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:618)
	at javax.crypto.Cipher.doFinal(Cipher.java:2074)
	at eu.fulldisclosure.android.luks.MainActivity.run(MainActivity.java:251)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by full-disclosure** [comment]
What is your Android OS version and the phone vendor?

**Comment by cynojien** [comment]
My apologies!

Life picked up and I forgot to respond to this.

The issue was not related to this app at all. I have a USB keyboard/mouse app that works by adding a USB gadget device via root. Once the phone is rebooted after use this app work perfect.

https://github.com/Arian04/android-hid-client

If anyone trying to use both of these apps is having the same crash issue you have to reboot after using the HID Client app to use this LUKS app.
